<?php if ( isset($datosSession) && count($datosSession) > 0 ) { ?>
    
<?php 
        //var_export($datosSession);

    } ?>
<?php
/*
$form = $this->form;

$campo = $form->get('cedula');
echo "<script>";
echo "var criterioPersona = '<div class=\"col-md-2\">".$this->formselect($campo)."</div>'";
echo "</script>";
*/



echo "<script>";
foreach ( $datosform as $k => $info ){
    $jsVar = "var $k = [";
    $jsVarId = "var ".$k."_id = [";
    foreach ($info as $kk => $datos){
        
        if ( $k == "tipoIncapacidad" ){
            $jsVar .= '"'.$datos->tipoincapacidad.'",';
            $jsVarId .= $datos->id_tipoincapacidad.",";
        }
        
        if ( $k == "sucursales" ){
            $jsVar .= '"'.$datos->sucursal.'",';
            $jsVarId .= $datos->id_sucursal.",";
        }

        if ( $k == "epss" ){
            $jsVar .= '"'.$datos->nombre_eps.'",';
            $jsVarId .= $datos->id_eps.",";
        }

        
    }
    $jsVar .= "];";
    $jsVarId .= "];";
    
    //echo "$k<br>";
    echo $jsVarId;
    echo $jsVar;
}
echo "</script>";

$title = 'Incapacidades';
$this->headTitle($title);


?><span>Consultar Incapacidades</span>
<span style="float:right;">
<span>
	<select id="select_reporte">
		<option>Fechas</option>
		<option>Dias</option>
		<option>Eps</option>
	</select>
	<a class="btn btn-success" onclick="exportarReporte();" title="Generar Reporte">Exportar</a>
</span>
    <a class="btn btn-info" href="<?= $this->url('add_incap', array('action' => 'index')) ?>" title="Adicionar nueva incapacidad">Nueva Incapacidad</a>
</span>


<?php //echo $this->form()->openTag($form); ?>
    
      
    <?php 
    
    $criterios = ["Persona",
                    "Sucursal",
                    "Eps",
                    "No. Incapacidad",
                    "Tipo Incapacidad",
                    "Diagnostico",
                    "Fecha Inicial",
                    "Fecha Final",
                    "Dias Totales",
                    "Dias Empresa",
                    "Dias Eps",
                    "Dias Arl",
        
    ];
    
    asort($criterios);
    
    echo '<div id="parabusqueda">Adicionar criterio de busqueda:'; 
    
    echo '<select id="criterios" class="custom-select">'; //onchange="addCriteria(this.value);"
    echo '<option value="">Seleccione...</option>';
    foreach ( $criterios as $key => $criterio ) {
        echo '<option value="'.$key.'">'.$criterio.'</option>';
    }
    echo '</select>
        
         <span onclick="addCriteria()"><img src="/img/incap/add.png" width="20px" style="cursor:pointer;" title="Añadir Criterio" /></span>
         <span onclick="buscar()"><img src="/img/incap/search.png" width="20px" style="cursor:pointer;" title="Buscar..." /></span>
         
        
        ';
    echo '</div>';
    
    echo '<form id="formbusqueda">';
    echo '</form>';
    
    ?>
    
<br />    
<div id="incapacidadesEncontradas"></div>
<div id="view_incap" title="Incapacidad" ></div>
  <script>
  $( function() {
	    $( "#view_incap" ).dialog({
	      autoOpen: false,
	      width: "80%",
	      show: {
	        effect: "blind",
	        duration: 1000
	      },
	      hide: {
	        effect: "explode",
	        duration: 1000
	      }
	    });
	 
	    
	  } );
  </script>
<!--  
<table class="table">
<tr>
    <th>Nuemro</th>
    <th>Tipo</th>
    <th>&nbsp;</th>
</tr>
<?php /* foreach ($albums as $album) : ?>
    <tr>
        <td><?= $this->escapeHtml($album->title) ?></td>
        <td><?= $this->escapeHtml($album->artist) ?></td>
        <td>
            <a href="<?= $this->url('album', ['action' => 'edit', 'id' => $album->id]) ?>">Edit</a>
            <a href="<?= $this->url('album', ['action' => 'delete', 'id' => $album->id]) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach; */ ?>
</table>

-->