<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) 
                        ->prependStylesheet($this->basePath('css/font-awesome.min.css'))
                        ->prependStylesheet($this->basePath('css/pe-icon-7-stroke.css'))
                        ->prependStylesheet($this->basePath('css/lightbox.min.css'))
                        ->prependStylesheet($this->basePath('css/style.default.css'))
                        ->prependStylesheet($this->basePath('css/custom.css'))
                        ->prependStylesheet($this->basePath('css/select2.min.css'))
                        ->prependStylesheet($this->basePath('css/sweetalert.css'))
                        ->prependStylesheet($this->basePath('css/jquery-ui.css'))
                        ->prependStylesheet($this->basePath('css/datepicker.css'))
                        ; ?>

        <!-- Scripts -->
       <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/datepicker.js'))
            ->prependFile($this->basePath('js/moment.js'))
            ->prependFile($this->basePath('js/front.js'))
            ->prependFile($this->basePath('js/lightbox.min.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.cookie.js'))
            ->prependFile($this->basePath('js/select2.min.js'))
            ->prependFile($this->basePath('js/sweetalert.min.js'))
            ->prependFile($this->basePath('js/jquery-ui.js'))
            ; ?>

        <!----webfonts---->
		<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,700">
		
		<!-- Tweaks for older IEs--><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
		
	<?php if( !isset($this->logueado) || ( isset($this->logueado) && !$this->logueado) ) { ?>  
	<script>   
    $(function(){
     $("#btn_login").click(function(){
     var url = "<?= $this->url('login', array('action' => 'authenticate')); ?>"; // El script a dónde se realizará la petición.
        $.ajax({
               type: "POST",
               url: url,
               data: $("#form-login").serialize(), // Adjuntar los campos del formulario enviado.
               success: function(data)
               {
            	   var res = JSON.parse(data);
            	   
            	   if(res.acceso == false){
					  alert("Acceso no autorizado.");	
                   } else {
                      self.location.reload();
                   }
            	   
                   //$("#container").html(data); // Mostrar la respuestas del script PHP.
               }
             });
    
        return false; // Evitar ejecutar el submit del formulario.
     });
    });
    </script>
		<?php } else { ?>
				<script> 
				$(function(){
                 $("#btn_logout").click(function(){
                     
                 var url = "<?= $this->url('login', array('action' => 'logout')); ?>"; // El script a dónde se realizará la petición.
                    $.ajax({
                           type: "POST",
                           url: url,
                           data: 'logout=salir',
                           success: function(data)
                           {
                        	   var res = JSON.parse(data);
                        	   
                        	   if(res.loguot == false){
            					  alert("Error al cerrar la session.");	
                               } else {
                                  self.location.reload();
                               }
                        	   
                               //$("#container").html(data); // Mostrar la respuestas del script PHP.
                           }
                         });
                
                    return false; // Evitar ejecutar el submit del formulario.
                 });
                });
                </script>
		<?php } ?>
    </head>
    
    
    
    <body>
        <!-- navbar-->
        
    <header class="header">
      <div role="navigation" class="navbar navbar-default">
        <div class="container">
          <div class="navbar-header"><a href="<?= $this->url('home') ?>" class="navbar-brand">INCAP.</a>
            <div class="navbar-buttons">
              <button type="button" data-toggle="collapse" data-target=".navbar-collapse" class="navbar-toggle navbar-btn">Menu<i class="fa fa-align-justify"></i></button>
            </div>
          </div>
          <div id="navigation" class="collapse navbar-collapse navbar-right">
            <ul class="nav navbar-nav">
              <li class="<?= ( (strcmp($this->layout()->controllerName,'index') == 0 ) || (strcmp($this->layout()->controllerName,'') == 0 ) )?'active':'' ?>"><a href="<?= $this->url('home') ?>">Home</a></li>
              
              <?php if ( isset($this->logueado) && $this->logueado ) { ?>  
            		<li class="dropdown <?= ( (preg_match('/add_incap|list_incap/', $this->layout()->controllerName)) !== 0 ) ? 'active' : '' ?>"><a href="#" data-toggle="dropdown" class="dropdown-toggle">Incapacidades <b class="caret"></b></a>
            		    <!--  <a href="<?= $this->url('add_incap', array('action' => 'index')); ?>">Add Incap</a></li> -->
            		    <ul class="dropdown-menu multi-level" role="menu" aria-labelledby="dropdownMenu" style=" margin-top: -1px;">
                          
                          <li class="dropdown-submenu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Incapacidad</a>
                            <ul class="dropdown-menu">
                            
                              <li><a href="<?= $this->url('list_incap', array('action' => 'index')); ?>">Consultar</a></li>
                              <li><a href="<?= $this->url('add_incap', array('action' => 'index')); ?>">Agregar</a></li>
                              <li><a href="<?= $this->url('upload_incap', array('action' => 'index')); ?>">Desde Archivo</a></li>
                        	</ul>
                       	</li>
                        <li class="dropdown-submenu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Administrar</a>
                            <ul class="dropdown-menu">
                                <li><a href="<?= $this->url('causales', array('action' => 'index')); ?>">Causales</a></li>
                              	<li><a href="#">Diagnosticos</a></li>
                              	<li><a href="#">Eps</a></li>
                              	<li><a href="#">Personas</a></li>
                              	<li><a href="#">Sucursales</a></li>
                              	<li><a href="#">Tipos Incap</a></li>
                                
                            </ul>
                        </li>
                          <!--  
                          
                          <li class="dropdown-submenu">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown</a>
                                    <ul class="dropdown-menu">
                                        <li class="dropdown-submenu">
                                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown</a>
                                            <ul class="dropdown-menu">
                                                <li><a href="#">Action</a></li>
                                                <li><a href="#">Another action</a></li>
                                                <li><a href="#">Something else here</a></li>
                                                <li class="divider"></li>
                                                <li><a href="#">Separated link</a></li>
                                                <li class="divider"></li>
                                                <li><a href="#">One more separated link</a></li>
                                            </ul>
                                        </li>
                                    </ul>
                                </li>
                          
                          <li class="dropdown"><a href="#" >Administrar</a>
                            <ul class="dropdown-menu">
                              <li><a href="#">Causales</a></li>
                              <li><a href="#">Diagnosticos</a></li>
                              <li><a href="#">Eps</a></li>
                              <li><a href="#">Personas</a></li>
                              <li><a href="#">Sucursales</a></li>
                              <li><a href="#">Tipos de Incapacidad</a></li>
                            </ul>
                          </li>
                          -->
                        
                        </ul>
          	  
              
              <!-- 
              <li class="dropdown"><a href="#" data-toggle="dropdown" class="dropdown-toggle">Administrar <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Causales</a></li>
                  <li><a href="#">Diagnosticos</a></li>
                  <li><a href="#">Eps</a></li>
                  <li><a href="#">Personas</a></li>
                  <li><a href="#">Sucursales</a></li>
                  <li><a href="#">Tipos de Incapacidad</a></li>
                </ul>
              </li>
              -->
              <?php } ?>
              <li><a href="contact.html">Contact</a></li>
            </ul>
          <?php if ( !isset($this->logueado) || ( isset($this->logueado) && !$this->logueado ) ) { ?>  
            <a href="#" data-toggle="modal" data-target="#login-modal" class="btn navbar-btn btn-ghost"><i class="fa fa-sign-in"></i>Log in</a>
          <?php } else { ?>
          			<a href="javascript:;"  class="btn navbar-btn btn-ghost" id="btn_logout"><i class="fa fa-sign-in"></i>Salir</a>
          <?php } ?>
          </div>
        </div>
      </div>
    </header>
    <!-- *** LOGIN MODAL ***_________________________________________________________
    -->
    <?php if( !isset($this->logueado) || ( isset($this->logueado) && !$this->logueado ) ) { ?> 
    <div id="login-modal" tabindex="-1" role="dialog" aria-labelledby="Login" aria-hidden="true" class="modal fade">
      <div class="modal-dialog modal-sm">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" data-dismiss="modal" aria-hidden="true" class="close">×</button>
            <h4 id="Login" class="modal-title">Acceso</h4>
          </div>
          <div class="modal-body">
            <form action="/login/authenticate" method="post" id="form-login">
              <div class="form-group">
                <input id="usuario" name="usuario" type="text" placeholder="usuario" class="form-control">
              </div>
              <div class="form-group">
                <input id="clave" name="clave" type="password" placeholder="clave" class="form-control">
              </div>
              <p class="text-center">
                <input type="submit" id="btn_login" class="btn btn-primary" value="Log In">
              </p>
            </form>
            <p class="text-center text-muted">Not registered yet?</p>
            <p class="text-center text-muted"><a href="#"><strong>Register now</strong></a>! It is easy and done in 1 minute and gives you access to special discounts and much more!</p>
          </div>
        </div>
      </div>
    </div>
    <?php } ?>
    <!-- *** LOGIN MODAL END ***-->
    
     <div class="container-fluid" id="container">
    
            <?php echo $this->content; ?>
            <hr>
            
    </div>
    <footer class="footer">
      
      <div class="footer__copyright">
        <div class="container">
          <div class="row">
            <div class="col-md-6">
              <p>&copy;2016 Best company</p>
            </div>
            <div class="col-md-6">
              <p class="credit">Template by <a href="https://bootstrapious.com/free-templates" class="external">Bootstrapious.com</a></p>
              <!-- Please do not remove the backlink to us unless you support us at https://bootstrapious.com/donate. It is part of the license conditions. Thank you for understanding :)-->
            </div>
          </div>
        </div>
      </div>
    </footer>
      <!-- Google Analytics: change UA-XXXXX-X to be your site's ID.-->
    <!---->
    
    <?php if ( strcmp($this->layout()->controllerName,'add_incap') == 0 || strcmp($this->layout()->controllerName,'list_incap') == 0) { ?>
    <?php  echo $this->inlineScript()->prependFile($this->basePath('js/incapacidades.js')); ?>
    <!-- SELECT2 -->
    <script type="text/javascript">
        $('#tipoIncap').select2();
        $('#sucursal').select2();
        $('#prorroga').select2();
        $('#eps').select2();

  		var url_search_dg = "<?= $this->url('add_incap', array('action' => 'buscarDiagnosticos')); ?>"; // El script a dónde se realizará la petición.
  		var url_search_aso = "<?= $this->url('add_incap', array('action' => 'buscarAsociados')); ?>"; // El script a dónde se realizará la petición.
  		var url_search_prorroga = "<?= $this->url('add_incap', array('action' => 'buscarIncapacidades')); ?>"; // El script a dónde se realizará la petición.
  		var url_search_incap = "<?= $this->url('list_incap', array('action' => 'buscarIncapacidades')); ?>"; // El script a dónde se realizará la petición.
  		var url_view_incap = "<?= $this->url('list_incap', array('action' => 'verIncapacidad')); ?>"; // El script a dónde se realizará la petición.
  		var url_get_report = "<?= $this->url('list_incap', array('action' => 'generarReporte')); ?>"; // El script a dónde se realizará la petición.

  		$("#diagnostico").select2({
  			//tags: true,
  		    //multiple: false,
  		    //tokenSeparators: [',', ' '],
  		    minimumInputLength: 2,
  		    //minimumResultsForSearch: 10,
  		    
  			//minimumInputLength: 2,
  		    //tags: [],
                    allowClear: true,
                    placeholder: "Buscar Doagnostico...",			

  		    ajax: {
  		        url: url_search_dg,
  		        dataType: "json",
  		        type: "POST",
  		        data: function (params) {

  		            var queryParameters = {
  		                term: params.term
  		            }
  		            return queryParameters;
  		        },
  		        
    		      processResults: function (data) {
    	  		        return {
    	  		            results: $.map(data, function (item) {
    	  		                return {
    	  		                    text: item.completeName,
    	  		                    id: item.id
    	  		                }
    	  		            })
    	  		        };
    	  		    }
  		    }
  		});

  		$("#cedula").select2({
  		    minimumInputLength: 2,
                    allowClear: true,
                    placeholder: "Buscar Persona...",			
                    ajax: {
  		        url: url_search_aso,
  		        dataType: "json",
  		        type: "POST",
  		        data: function (params) {

  		            var queryParameters = {
  		                term: params.term
  		            }
  		            return queryParameters;
  		        },
  		        
    		      processResults: function (data) {
    	  		        return {
    	  		            results: $.map(data, function (item) {
    	  		                return {
    	  		                    text: item.completeName,
    	  		                    id: item.id
    	  		                }
    	  		            })
    	  		        };
    	  		    },
      	  		  
  		    },
    		  
  		});
                
                $("#prorroga").select2({
  		    minimumInputLength: 2,
                    allowClear: true,
                    placeholder: "Buscar Incapacidad...",
  		    ajax: {
  		        url: url_search_prorroga,
  		        dataType: "json",
  		        type: "POST",
  		        data: function (params) {

                            var queryParameters = "";
                            $("select[id*=cedula]").each(function(){
                               if ( $(this).val() != "" ) {
                                   queryParameters = {
                                        term: params.term,
                                        asociado: $(this).val()
                                    }

                                    
                               } 
                            });
                            //alert(queryParameters);
                            return queryParameters;
  		            
  		        },
    		      processResults: function (data) {
    	  		        return {
    	  		            results: $.map(data, function (item) {
    	  		                return {
    	  		                    text: item.completeName,
    	  		                    id: item.id
    	  		                }
    	  		            })
    	  		        };
    	  		    }
  		    }
  		});

                $(document.body).on("change","#prorroga",function(){
                    analizarFechas();
                });

  		//$("#cedula").select2("val", [{"id":"51","text":"Henry Ford"}]);
      //alert(123);
      //$("#cedula").select2().select2("val", null);
      //$("#cedula").select2().select2("val", '51');
  		
      //$("#cedula").val("51").trigger("change");
      
	</script>
	<?php } ?>
    <script>
      (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
      function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
      e=o.createElement(i);r=o.getElementsByTagName(i)[0];
      e.src='//www.google-analytics.com/analytics.js';
      r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
      ga('create','UA-XXXXX-X');ga('send','pageview');
    </script>
    </body>
</html>
