<span>
    <span class="text-primary"><big>DIAGNOSTICOS</big></span>
<br>
<span>
    <span class="col-md-2">
        <input type="text" name="buscarDiagnostico" id="buscarDiagnostico" class="form-control" value="<?= (isset($paramBuscar)) ? $paramBuscar : "" ?>">
    </span>
    <span class="col-md-1">    
	<a class="btn btn-success glyphicon glyphicon-search" onclick="buscarDiagnostico();" title="Buscar"></a>
    </span>
</span>
</span>
<span style="float:right;">
<!--
<span>
	<select id="select_reporte">
		<option>Fechas</option>
		<option>Dias</option>
		<option>Eps</option>
	</select>
	<a class="btn btn-success" onclick="exportarReporte();" title="Generar Reporte">Exportar</a>
</span>
<?= $this->url('diagnosticos', array('action' => 'nuevoDiagnostico')) ?>
-->
    <a class="btn btn-info" id="nuevo_diagnostico"  title="Adicionar nuevo Diagnostico">Nuevo Diagnostico</a>
</span>



<?php if ( isset($diagnosticos) && count($diagnosticos) > 0 ) { ?>
<table class="table" id="listaDiagnosticos">
    <thead>
    <tr>
        <th style="max-width: 100px">Sigla</th>
        <th>Nombre</th>
        <th>Modificar</th>
        <th>Eliminar</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($diagnosticos as $diag){?>
    <tr style="background-color:<?php echo $this->cycle(array("#F0F0F0","#FFFFFF"))->next()?>">
        <td><?=$diag->codigo_diagnostico?></td>
        <td><?=$diag->nombre_diagnostico?></td>
        <td><a class="btn btn-primary" href="<?=$this->basePath()?>/add_incap/index/<?=$diag->id_diagnostico?>">Modificar</a></td>
        <td><a class="btn btn-danger" href="<?=$this->basePath()?>/add_incap/<?=$diag->id_diagnostico?>">Eliminar</a></td>
        
    </tr>
    <?php } ?>
    </tbody>
</table>



<script>
    $(document).ready(function(){
        $("#listaDiagnosticos").paginationTdA({
            elemPerPage: 6
        });
    });
</script>

<?php } ?>








<div class="modal fade" id="modalDiagnostico" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div id= 'html_contentPop'></div>
      <div class="modal-footer">
        <!--<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>-->
        <br>&nbsp;
      </div>
    </div>
  </div>
</div>
<script>
    var url_new_dg = "<?= $this->url('diagnosticos', array('action' => 'nuevoDiagnostico')); ?>"; 
    var url_search_dg = "<?= $this->url('diagnosticos', array('action' => 'buscar')); ?>"; 
</script>