<p style="text-align: center">
    <form name="formAddDiag" id="formAddDiag">
        <table align="center">
            <tr>
                <td><label class="control-label" for="sigla">Sigla:</label></td>
                <td><input class="form-control" type="text" name="sigla" size="10"></td>
            </tr>
            <tr>
                <td><label class="control-label" for="nombre">Nombre:</label></td>
                <td><input class="form-control" type="text" name="nombre" size="30"></td>
            </tr>
        </table>
    </form>
</p>    


